[project]
name = "voidmasks"
authors = ["CryptoExplor"]
description = "VOIDMASKS â€” 100% on-chain schizocore SVG NFTs on Stacks"
telemetry = false
cache_dir = "./.cache"

[[project.requirements]]
contract_id = "SP2PABAF9FTAJYNFZH93XENAJ8FVY99RRM50D2JG9.nft-trait"

[contracts.voidmasks]
path = "contracts/voidmasks.clar"
clarity_version = 4
epoch = "latest"

[repl.analysis]
passes = ["check_checker"]

[repl.analysis.check_checker]
strict = false
trusted_sender = true
trusted_caller = false
callee_filter = false
