[project]
name = "voidmasks"
authors = ["CryptoExplor"]
description = "VOIDMASKS â€” 100% on-chain schizocore SVG NFTs on Stacks"
telemetry = false

[contracts.voidmasks]
path = "contracts/voidmasks.clar"
clarity_version = 4

[repl]
clarity_version = 4

[networks.testnet]
stacks_node_rpc_address = "https://stacks-node-api.testnet.stacks.co"
stacks_node_events_address = "https://stacks-node-api.testnet.stacks.co"
bitcoin_node_rpc_address = "https://bitcoin-node-api.testnet.stacks.co"
bitcoin_node_rpc_username = "user"
bitcoin_node_rpc_password = "password"

[networks.mainnet]
stacks_node_rpc_address = "https://stacks-node-api.mainnet.stacks.co"
stacks_node_events_address = "https://stacks-node-api.mainnet.stacks.co"
bitcoin_node_rpc_address = "https://bitcoin-node-api.mainnet.stacks.co"
bitcoin_node_rpc_username = "user"
bitcoin_node_rpc_password = "password"
